apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: kafka
spec:
  ports:
  - name: zookeeper-port
    nodePort: 30181
    port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - env:
        - name: ZOO_MY_ID
          value: '1'
        - name: ZOO_SERVERS
          value: server.1=0.0.0.0:2888:3888;2181
        - name: ZOO_STANDALONE_ENABLED
          value: 'true'
        image: zookeeper:3.7.0
        imagePullPolicy: IfNotPresent
        name: zookeeper
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
      nodeName: gke-two-node-cluster-node-pool-1-a8209908-vz7g
