apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: kafka
spec:
  ports:
  - name: kafka-broker
    nodePort: 32092
    port: 9092
    targetPort: 9092
  selector:
    app: kafka-broker
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - env:
        - name: KAFKA_CFG_BROKER_ID
          value: '1'
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service.kafka.svc.cluster.local:9092
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT
        image: bitnami/kafka:3.7.0
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092
        resources:
          limits:
            cpu: '1'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 4Gi
      hostname: kafka-broker
      nodeName: gke-two-node-cluster-node-pool-1-a8209908-vz7g
