apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow
  name: mlflow
spec:
  ports:
  - nodePort: 30500
    port: 5000
    targetPort: 5000
  selector:
    app: mlflow
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mlflow
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - args:
        - server
        - --backend-store-uri
        - sqlite:////mlartifacts/mlflow.db
        - --host
        - 0.0.0.0
        - --port
        - '5000'
        command:
        - mlflow
        image: ghcr.io/mlflow/mlflow:v2.0.1
        name: mlflow
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: '1'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 4Gi
        volumeMounts:
        - mountPath: /mlartifacts
          name: mlflow-storage
      nodeName: gke-two-node-cluster-node-pool-1-a8209908-0c5n
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: mlflow-disk
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
