apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-inferencia
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api-inferencia
  template:
    metadata:
      labels:
        app: api-inferencia
    spec:
      containers:
      - args:
        - -c
        - tail -f /dev/null
        command:
        - /bin/sh
        image: mgrodrigues001/api_flask_inferencia:inf_v8.0
        imagePullPolicy: Always
        name: api-inferencia
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - mountPath: /app
          name: app-storage
      nodeName: gke-two-node-cluster-node-pool-1-a8209908-0c5n
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: api-inferencia-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-inferencia-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-inferencia-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: api-update-disk
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
